<?php namespace BehatManager;

abstract class ScenarioResult {

  /**
   * The unique identifier for this test result.
   *
   * @var string
   */
  protected $id;

  /**
   * @var ScenarioNode
   */
  protected $scenario;

  /**
   * The duration of the testing run.
   *
   * @var float
   */
  protected $duration;

  /**
   * The number of assertions for this scenario.
   *
   * @var int
   */
  protected $assertions;

  /**
   * The message that was generated by Behat when running this scenario.
   * @var string
   */
  protected $message;

  /**
   * The status of the test result, TRUE if the test passed, FALSE if it failed.
   *
   * @var bool
   */
  protected $status;

  /**
   * A UNIX epoch integer representing when the test was run.
   *
   * @var int
   */
  protected $timestamp;

}
